--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Henry12960/CreativeManager
build-by-default: true
branches:
- main
projects:
  CreativeManager:
    path: ""
    icon: "CreativeManager.png"
...